name: Build the web book for all release branches

on:
  workflow_dispatch:
    inputs:
      release:
        description: Release this version
        type: boolean
        default: false
      publish:
        description: Package index to publish to
        type: choice
        options:
          - none
          - PyPI
      segment:
        description: Version segment to bump with Hatch
        type: string
        required: false
      build_current:
        description: Build current brancch
        type: boolean
        default: true
      build_1_19:
        description: Build 1.19
        type: boolean
        default: true
      build_1_18:
        description: Build 1.18
        type: boolean
        default: true

jobs:
  build_current:
    uses: ./.github/workflows/build_docs.yml
    if: inputs.build_current
    with:
      release: ${{ inputs.release }}
      publish: ${{ inputs.publish }}
      segment: ${{ inputs.segment }}
      build-group-id: 'current'

  build_1_19:
    uses: object-Object/HexMod/.github/workflows/build_docs.yml@1.19
    if: inputs.build_1_19
    with:
      release: ${{ inputs.release }}
      publish: ${{ inputs.publish }}
      segment: ${{ inputs.segment }}
      build-group-id: '1_19'

  build_1_18:
    # avoid cancellations from more than 2 jobs running in the same concurrency group at once
    needs: [build_current, build_1_19]
    if: inputs.build_1_18 && !cancelled()
    uses: object-Object/HexMod/.github/workflows/build_docs.yml@1.18
    with:
      release: ${{ inputs.release }}
      publish: ${{ inputs.publish }}
      segment: ${{ inputs.segment }}
      build-group-id: '1_18'
